#import "@/graphql/fragments/CategoryFragment.gql"

query Categories(
  $where: CategoryRecordsWhereWhereConditions = {}
  $whereTotal: CategoryRecordsTotalWhereWhereConditions = {}
) {
  categories(orderBy: [{ column: IS_INCOME, order: ASC }]) {
    data {
      ...CategoryFragment

      records(orderBy: [{ column: CREATED_AT, order: DESC }], where: $where) {
        created_at
        id
        note
        sum
      }

      recordsTotal(where: $whereTotal)
    }
  }
}
