#import "@/graphql/fragments/CategoryFragment.gql"
#import "@/graphql/fragments/RecordFragment.gql"

query FirstRecord {
  records(first: 1, orderBy: [{ column: CREATED_AT, order: ASC }]) {
    data {
      category {
        ...CategoryFragment
      }

      ...RecordFragment
    }
  }
}
