#import "@/graphql/fragments/UserFragment.gql"

mutation Login($password: String!, $username: String!) {
  login(input: { username: $username, password: $password }) {
    access_token
    user {
      ...UserFragment
    }
  }
}
