#import "@/graphql/fragments/SnapshotFragment.gql"

query Snapshots($first: Int, $orderBy: [QueryRevisesOrderByOrderByClause!] = [{ column: CREATED_AT, order: DESC }]) {
  snapshots: revises(first: $first, orderBy: $orderBy) {
    data {
      ...SnapshotFragment
    }

    paginatorInfo {
      total
      lastPage
    }
  }
}
