query Snapshots($first: Int, $orderBy: [QueryRevisesOrderByOrderByClause!] = [{ column: CREATED_AT, order: DESC }]) {
  snapshots: revises(first: $first, orderBy: $orderBy) {
    data {
      balance
      created_at
      id
      note
    }

    paginatorInfo {
      total
      lastPage
    }
  }
}
